version: '3'
services:
  frontend:
    image: frontendapp
    environment:
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
      - SPOTIFY_REDIRECT_URI=${SPOTIFY_REDIRECT_URI}
      - ATLAS_URI=${ATLAS_URI}
    ports:
      - "3000:3000" 
  backend:
    image: backendapp
    ports:
      - "3001:3001" 